import Head from "next/head";
import Image from "next/image";
import { Outfit } from "next/font/google";
import { useEffect } from "react";
import Hero from "@/ui/Hero";
import About from "@/ui/About";
import Exp from "@/ui/Exp";
// import Exp2 from "@/ui/Exp2";

const outfit = Outfit({ subsets: ["latin"] });

export default function Home() {

  // useEffect( () => {

  //   (

  //     async () => {

  //         const LocomotiveScroll = (await import('locomotive-scroll')).default

  //         const locomotiveScroll = new LocomotiveScroll();

  //     }

  //   )()

  // }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={outfit.className}>
        <Hero/>
        <About/>
        <Exp/>
      </main>
    </>
  );
}
